#!/usr/bin/python2
#coding=utf-8
#Dev: Faxel

# Le credit pour ce code va a Mr Faxel
# Si vous voulez prendre Le credit pour ce code Voyez Faster Axel.


import base64
import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize,fileinput
from time import sleep
from sys import exit

os.system("clear")
print("\t[fissure de masse en base64]")
script = raw_input(" Entrer le script a decrypter > ")
resultat = raw_input(" Nommer le resusltat > ")
print("Attente du decryptage ...")
print("-"*40)
try:
	ouverture = open(script).readlines()
except:
	print("N'a pas réussi à ouvrir la liste")
	exit()
sauve=[]
jabot=[]
sauvegarde=open(resultat,'w')
for k in ouverture:
	try:
		print("Resultat -> ",base64.b64decode(k.split('\n')[0]))
		resul = base64.b64decode(k.split('\n')[0])
		jabot.append(resul)
		sleep(00.01)
	except:
		print ("Rembourrage incorrect")
		sauve.append(k)
		sleep(00.01)
print("-"*40)
for result in j:
	sauvegarde.write(result.split('\n')[0]+"\n")
sauvegarde.close()
print(" Réussite totale:",len(jabot))
print(" Emplacement :",sauvegarde)
print("-"*40)
print(" Echec:",len(sauve))
for t in sauve:
	print ("Echec:",t.replace('\n',''))
print("-"*40)
