#!usr/bin/python2
# coding=utf-8 
# Faxel

import marshal as mc
import zlib, base64, time, sys, os ,datetime, random
logo1 = """\033[1;96m       ╔═╗┬─┐┬ ┬┌─┐┌┬┐┌─┐┌─┐┌─┐ \n\033[1;96m       ║  ├┬┘└┬┘├─┘ │ ├─┤│ ┬├┤  \n\033[1;96m       ╚═╝┴└─ ┴ ┴   ┴ ┴ ┴└─┘└─┘ """
logo = """\033[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●     \n\033[38;5;214m•_  _ ____ \033[1;97m _  _ ____ ____ _  _\033[1;32m ____ ____   _  _• \n\033[38;5;214m•|\/| |__/ \033[1;97m |__| |__| |    |_/ \033[1;32m |___ |__/   |_/ • \n\033[38;5;214m•|  | |  \ \033[1;97m |  | |  | |___ | \_\033[1;32m |___ |  \ __| \_• \n\033[38;5;214m●▬▬▬▬▬▬▬▬๑\033[1;97m●▬▬▬▬▬▬๑۩۩๑▬▬▬▬▬▬●●▬▬▬▬▬\033[1;32m▬▬▬▬๑۩۩๑▬▬▬▬▬▬●\n\033[1;97m╔═════════════════════════════════════════════╗\n\033[1;97m║\033[1;91m[\033[1;93m**\033[1;91m]\033[38;5;95m      Developpeur \033[1;97m:\033[38;5;214m  Faxel           \033[1;91m[\033[1;93m**\033[1;91m]\033[1;97m║\n\033[1;97m╚═════════════════════════════════════════════╝
"""	
os.system("clear")
print(logo)
print(logo1) 

try:
    dmd = raw_input('\033[1;93mScript a crypter \033[1;91m: \033[1;97m')
    reoriente = mc.dumps(compile(open(dmd, 'rb').read(), '<string>', 'exec'))
except:
    print ("\033[1;91mFichier introuvable ou invalide")
    sys.exit()

antoine = base64.b16encode(zlib.compress(reoriente))
codeur1 = "\n# -*- coding: UTF-8 -*-\n'''\033[1;94mFax-Cryptage {}\n\033[1;95mDev \033[1;91m: Faxel \n'''\nimport sys\nimport zlib as zn\nfrom base64 import *\nimport marshal as mc\n\ndef main_code():\n    exec(mc.loads(zn.decompress(b16decode('{}'))))\n\nmain_code()\n".format(time.ctime(), antoine)
codeur2 = '\nimport marshal , base64\nexec(marshal.loads(base64.b16decode("{}")))\n'.format(base64.b16encode(mc.dumps(compile(codeur1, '<string>', 'exec'))))
codeur3 = '\nimport marshal , base64\nexec(marshal.loads(base64.b32decode("{}")))\n'.format(base64.b32encode(mc.dumps(compile(codeur2, '<string>', 'exec'))))
supcode = base64.b16encode(mc.dumps(compile(codeur3, '<string>', 'exec')))
monique = base64.b32encode(mc.dumps(compile('\nimport os\nos.system("rm -rf *.pyc")\n', '<string>', 'exec')))
jesus = "\n'''\n\033[1;95mDev \033[1;91m: Faxel\n\033[1;96mCryptage avec Fax-encodage\n'''\nimport marshal , base64 , os\nexec(marshal.loads(base64.b32decode(b'{}')))\nexec(marshal.loads(base64.b16decode('{}')))\n".format(monique, supcode)
print '\033[1;94mAncienne taille\033[1;91m :\033[1;93m {} Bytes'.format(len(reoriente))
with open('__main__.py', 'wb') as es:
    es.write(jesus)
os.system('zip {} {}'.format('F-' + dmd, '__main__.py'))
print '\033[1;96mNouvelle taille\033[1;91m :\033[1;92m {} Bytes'.format(len(open('F-' + dmd, 'rb').read()))
os.system('rm {}'.format('__main__.py'))
print '\033[1;97mGenerer un script crypter \033[1;91m: \033[1;92m{}'.format('F-' + dmd)
