#!/bin/bash
sleep 2
figlet Faxel | lolcat

$link2 = 'https://www.youtube.com/channel/UCdmpFkmXAoSpG9fu1x0VPWw';

Sleep 6
echo $'\[\e[32m\]S'IL VOUS PLAÎT ABONNEZ YOUTUBE\[\e[0m\]'
sleep 4
echo $'\[\e[33m\]LISTE DE MOTS GÉNÉRÉE PAR FAXEL\[\e[0m\]'
sleep 4


string=( {a..z} )
for x in ${string[@]}; do
for y in ${string[@]}; do
for z in ${string[@]}; do
for w in ${string[@]}; do
for k in ${string[@]}; do
#for q in ${string[@]}; do
echo $x$y$z$w$k

done done done done done
